"""
Build script — fetches data, runs analytics, dumps to web/data.json.
Run this any time you want to refresh the dashboard.

Usage:  python build.py
Output: web/data.json
"""

import json
import sys
import os
import warnings
from pathlib import Path
from datetime import datetime

warnings.filterwarnings("ignore")

# Force UTF-8 output on Windows (otherwise GBK breaks on ✓ etc.)
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

# Workaround for SSL cert path issues with yfinance/curl_cffi
os.environ.setdefault("CURL_CA_BUNDLE", "")
os.environ.setdefault("REQUESTS_CA_BUNDLE", "")

import pandas as pd
import numpy as np

sys.path.insert(0, str(Path(__file__).parent))
from data_fetcher import get_master_data
from analytics   import run_full_analysis, latest_snapshot


def df_to_records(df: pd.DataFrame, cols=None) -> list[dict]:
    """Convert DataFrame to list of {date, col1, col2, ...} dicts, JSON-safe."""
    if cols:
        df = df[[c for c in cols if c in df.columns]]
    out = df.copy()
    out.index = out.index.strftime("%Y-%m-%d")
    out = out.reset_index().rename(columns={"index": "date"})
    out = out.replace({np.nan: None})
    return out.to_dict(orient="records")


def main():
    print("→ Fetching market data (may take 30-60s)...")
    master_df, quality = get_master_data()

    if master_df.empty:
        print("✗ No data fetched.")
        sys.exit(1)

    print(f"✓ Loaded {len(master_df)} rows. Running analytics...")
    df = run_full_analysis(master_df)
    snap = latest_snapshot(df)

    payload = {
        "generated_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "snapshot":     snap,
        "quality":      {k: round(float(v), 3) for k, v in quality.items()},
        "series":       df_to_records(df, cols=[
            "us_2y", "cn_2y", "yield_spread",
            "usdcny", "usdcnh", "pboc_fix", "onoffshore_gap",
            "dxy", "dxy_ret",
            "raw_carry", "carry_ma20", "carry_ma60", "carry_ma120",
            "carry_pct_rank", "carry_pct_rank_2y",
            # v3.1 — money-market funding rates + hedged-carry proxy
            "shibor_1y", "us_1y", "mm_spread", "mm_carry",
            "cip_dev_pct", "hedged_carry_proxy", "hedged_carry_pct_rank",
            "cip_fair_spot", "cip_deviation",
            "reg_predicted", "reg_residual", "reg_predicted_uni", "reg_residual_uni",
            "reg_beta_spread", "reg_beta_dxy", "reg_r2",
            "mispricing_score",
            "alpha_cny_dxy", "expected_fix",
            "fixing_bias", "fixing_bias_raw",
            "bias_20d_mean", "bias_60d_mean",
            "defense_intensity", "policy_score",
            "composite_score", "composite_score_smooth",
        ]),
    }

    out_path = Path(__file__).parent / "docs" / "data.json"
    out_path.parent.mkdir(exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2, default=str, ensure_ascii=False)

    size_kb = out_path.stat().st_size // 1024
    print(f"✓ Wrote {out_path} ({size_kb} KB)")
    print(f"  Latest date:        {snap['date']}")
    print(f"  Composite score:    {snap['composite_score']}/100")
    print(f"  USD/CNY:            {snap['usdcny']}")
    print(f"  Raw carry:          {snap['raw_carry']}%")

    append_build_log(snap, quality, size_kb, len(df))


def append_build_log(snap, quality, size_kb, n_rows):
    """Append a structured entry to BUILD_LOG.md after each successful build."""
    log_path = Path(__file__).parent / "BUILD_LOG.md"
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    q_summary = " · ".join(
        f"{k} {'✅' if v > 0.8 else '⚠️' if v > 0.3 else '❌'}{v*100:.0f}%"
        for k, v in quality.items()
    )

    score = snap.get("composite_score", "—")
    usdcny = snap.get("usdcny", "—")
    carry = snap.get("raw_carry", "—")
    bias = snap.get("fixing_bias", "—")
    try:
        bias_pips = f"{float(bias)*10000:.0f} pips"
    except (ValueError, TypeError):
        bias_pips = "—"

    entry = (
        f"\n## {now}\n"
        f"- **Data date:** {snap.get('date', '—')}\n"
        f"- **Rows:** {n_rows} · **Payload:** {size_kb} KB\n"
        f"- **Composite Score:** {score}/100\n"
        f"- **USD/CNY:** {usdcny} · **Raw Carry:** {carry}% · **Fixing Bias:** {bias_pips}\n"
        f"- **Coverage:** {q_summary}\n"
        f"---\n"
    )

    header = "# Build Log\n\n> Auto-generated by `build.py` on each successful run.\n\n---\n"

    if log_path.exists():
        existing = log_path.read_text(encoding="utf-8")
        # Insert new entry after the header separator
        if "---\n" in existing:
            parts = existing.split("---\n", 1)
            content = parts[0] + "---\n" + entry + (parts[1] if len(parts) > 1 else "")
        else:
            content = existing + entry
    else:
        content = header + entry

    log_path.write_text(content, encoding="utf-8")
    print(f"✓ Appended build log → BUILD_LOG.md")


if __name__ == "__main__":
    main()
